--[[
██╗  ██╗███████╗██╗  ██╗ █████╗     ██╗  ██╗██╗   ██╗██████╗ 
██║  ██║██╔════╝╚██╗██╔╝██╔══██╗    ██║  ██║██║   ██║██╔══██╗
███████║█████╗   ╚███╔╝ ███████║    ███████║██║   ██║██████╔╝
██╔══██║██╔══╝   ██╔██╗ ██╔══██║    ██╔══██║██║   ██║██╔══██╗
██║  ██║███████╗██╔╝ ██╗██║  ██║    ██║  ██║╚██████╔╝██████╔╝
╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝    ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ 
If you are reading this... How did you get here? ANYWAY U NOT GETTING A FREE SCRIPT!1! You're either perfect or you're not me.                
]]--

local PlaceId = game.PlaceId

-- Beaks
if PlaceId == 122678592501168 then
    script_key=script_key;
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/c1af715fb5cef92216c02bab058d7050.lua"))()
end

-- Grow a Garden
if PlaceId == 126884695634066 then
    script_key=script_key;
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/bbec920857e855e25145e8e73278fdc0.lua"))()
end

-- Brainrot Evolution
if PlaceId == 111989938562194 then
    script_key=script_key;
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/d01c4774a11befb3205e3dc3c5c5e48a.lua"))()
end

-- Untitled Drill Game
if PlaceId == 87700573492940 then
    script_key=script_key;
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/72a2e5d817aaa0f7b969b103e44cd507.lua"))()
end
